export const partnershipDetailsCopy = {
  fr: {
    unknown: "Non communiqué",
    unofficialBadge: "À confirmer – source étudiante non officielle",
    nanterreWarning:
      "Les informations relatives aux partenariats de l’Université Paris Nanterre sont issues d’un document étudiant non officiel et peuvent varier selon les promotions. Les universités partenaires, le nombre de places, les bourses et les modalités doivent être confirmés auprès du master ou de l’université.",
    studentWarning: (university: string) =>
      `Les informations relatives à ${university} proviennent d’un retour étudiant non officiel et doivent être confirmées auprès de l’université ou du programme.`,
    labels: {
      faculty: "Faculté",
      programType: "Type de programme",
      programName: "Nom du programme",
      partnershipType: "Type de partenariat",
      application: "Candidature",
      partnerRegion: "Partenaire (pays/continent)",
      duration: "Durée",
      language: "Langue",
      requiredLevel: "Niveau requis",
      summary: "Résumé",
      sourceNote: "Source (note)",
      seatPolicy: "Politique de places",
      selection: "Sélection",
      internalCandidates: "Candidats internes",
      externalCandidates: "Candidats externes",
      admission: "Conditions d’admission",
      degrees: "Diplômes délivrés",
      nyBar: "Option New York Bar",
      conditions: "Conditions",
      extraFees: "Frais supplémentaires",
      documents: "Pièces à fournir",
      languageTests: "Tests de langue",
      seats: "Places",
      fees: "Frais",
      financialAid: "Aides financières",
      applicationYear: "Année de candidature",
      deadline: "Date limite",
      notes: "Remarques",
      officialSource: "Source officielle",
      pdf: "Documents (PDF)",
      missing: "Champs à compléter",
      location: "Localisation (France)",
      specialties: "Spécialités",
    },
    internal: "Interne (sélection par l’université française)",
    lsac: "Plateforme LSAC",
    externalAccepted: "Candidatures extérieures acceptées",
    externalRejected: "Candidatures extérieures non acceptées",
    open: "Ouvrir",
  },
  en: {
    unknown: "Not disclosed",
    unofficialBadge: "To confirm – unofficial student source",
    nanterreWarning:
      "Information about Université Paris Nanterre partnerships comes from an unofficial student document and may vary between cohorts. Partner universities, seats, scholarships, and procedures must be confirmed with the program or university.",
    studentWarning: (university: string) =>
      `Information about ${university} comes from unofficial student feedback and must be confirmed with the university or program.`,
    labels: {
      faculty: "Faculty",
      programType: "Program type",
      programName: "Program name",
      partnershipType: "Partnership type",
      application: "Application",
      partnerRegion: "Partner country/continent",
      duration: "Duration",
      language: "Language",
      requiredLevel: "Required level",
      summary: "Summary",
      sourceNote: "Source note",
      seatPolicy: "Seat policy",
      selection: "Selection",
      internalCandidates: "Internal applicants",
      externalCandidates: "External applicants",
      admission: "Admission requirements",
      degrees: "Degrees awarded",
      nyBar: "New York Bar option",
      conditions: "Requirements",
      extraFees: "Additional fees",
      documents: "Required documents",
      languageTests: "Language tests",
      seats: "Seats",
      fees: "Fees",
      financialAid: "Financial aid",
      applicationYear: "Application year",
      deadline: "Deadline",
      notes: "Notes",
      officialSource: "Official source",
      pdf: "Documents (PDF)",
      missing: "Missing fields",
      location: "Location (France)",
      specialties: "Specialties",
    },
    internal: "Internal selection by the French university",
    lsac: "LSAC platform",
    externalAccepted: "External applications accepted",
    externalRejected: "External applications not accepted",
    open: "Open",
  },
  es: {
    unknown: "No comunicado",
    unofficialBadge: "Por confirmar – fuente estudiantil no oficial",
    nanterreWarning:
      "La información sobre los convenios de Université Paris Nanterre procede de un documento estudiantil no oficial y puede variar según la promoción. Las universidades asociadas, plazas, becas y condiciones deben confirmarse con el máster o la universidad.",
    studentWarning: (university: string) =>
      `La información sobre ${university} procede de una fuente estudiantil no oficial y debe confirmarse con la universidad o el programa.`,
    labels: {
      faculty: "Facultad",
      programType: "Tipo de programa",
      programName: "Nombre del programa",
      partnershipType: "Tipo de convenio",
      application: "Candidatura",
      partnerRegion: "País/continente asociado",
      duration: "Duración",
      language: "Idioma",
      requiredLevel: "Nivel requerido",
      summary: "Resumen",
      sourceNote: "Nota de la fuente",
      seatPolicy: "Política de plazas",
      selection: "Selección",
      internalCandidates: "Candidatos internos",
      externalCandidates: "Candidatos externos",
      admission: "Requisitos de admisión",
      degrees: "Títulos otorgados",
      nyBar: "Opción New York Bar",
      conditions: "Requisitos",
      extraFees: "Costes adicionales",
      documents: "Documentos requeridos",
      languageTests: "Pruebas de idioma",
      seats: "Plazas",
      fees: "Costes",
      financialAid: "Ayudas económicas",
      applicationYear: "Año de candidatura",
      deadline: "Fecha límite",
      notes: "Notas",
      officialSource: "Fuente oficial",
      pdf: "Documentos (PDF)",
      missing: "Campos pendientes",
      location: "Ubicación (Francia)",
      specialties: "Especialidades",
    },
    internal: "Selección interna por la universidad francesa",
    lsac: "Plataforma LSAC",
    externalAccepted: "Candidaturas externas aceptadas",
    externalRejected: "Candidaturas externas no aceptadas",
    open: "Abrir",
  },
} as const
