export const partnershipDetailsCopy = {
  fr: {
    unknown: "Non communiqué",
    unofficialBadge: "À confirmer – source étudiante non officielle",
    nanterreWarning:
      "Les informations relatives aux partenariats de l’Université Paris Nanterre sont issues d’un document étudiant non officiel et peuvent varier selon les promotions. Les universités partenaires, le nombre de places, les bourses et les modalités doivent être confirmés auprès du master ou de l’université.",
    studentWarning: (university: string) =>
      `Les informations relatives à ${university} proviennent d’un retour étudiant non officiel et doivent être confirmées auprès de l’université ou du programme.`,
    labels: {
      faculty: "Faculté",
      programType: "Type de programme",
      programName: "Nom du programme",
      partnershipType: "Type de partenariat",
      application: "Candidature",
      partnerRegion: "Partenaire (pays/continent)",
      duration: "Durée",
      language: "Langue",
      requiredLevel: "Niveau requis",
      summary: "Résumé",
      sourceNote: "Source (note)",
      seatPolicy: "Politique de places",
      selection: "Sélection",
      internalCandidates: "Candidats internes",
      externalCandidates: "Candidats externes",
      admission: "Conditions d’admission",
      degrees: "Diplômes délivrés",
      nyBar: "Option New York Bar",
      conditions: "Conditions",
      extraFees: "Frais supplémentaires",
      documents: "Pièces à fournir",
      languageTests: "Tests de langue",
      seats: "Places",
      fees: "Frais",
      financialAid: "Aides financières",
      applicationYear: "Année de candidature",
      deadline: "Date limite",
      notes: "Remarques",
      officialSource: "Source officielle",
      pdf: "Documents (PDF)",
      missing: "Champs à compléter",
      location: "Localisation (France)",
      specialties: "Spécialités",
    },
    internal: "Interne (sélection par l’université française)",
    lsac: "Plateforme LSAC",
    externalAccepted: "Candidatures extérieures acceptées",
    externalRejected: "Candidatures extérieures non acceptées",
    open: "Ouvrir",
  },
  en: {
    unknown: "Not disclosed",
    unofficialBadge: "To confirm – unofficial student source",
    nanterreWarning:
      "Information about Université Paris Nanterre partnerships comes from an unofficial student document and may vary between cohorts. Partner universities, seats, scholarships, and procedures must be confirmed with the program or university.",
    studentWarning: (university: string) =>
      `Information about ${university} comes from unofficial student feedback and must be confirmed with the university or program.`,
    labels: {
      faculty: "Faculty",
      programType: "Program type",
      programName: "Program name",
      partnershipType: "Partnership type",
      application: "Application",
      partnerRegion: "Partner country/continent",
      duration: "Duration",
      language: "Language",
      requiredLevel: "Required level",
      summary: "Summary",
      sourceNote: "Source note",
      seatPolicy: "Seat policy",
      selection: "Selection",
      internalCandidates: "Internal applicants",
      externalCandidates: "External applicants",
      admission: "Admission requirements",
      degrees: "Degrees awarded",
      nyBar: "New York Bar option",
      conditions: "Requirements",
      extraFees: "Additional fees",
      documents: "Required documents",
      languageTests: "Language tests",
      seats: "Seats",
      fees: "Fees",
      financialAid: "Financial aid",
      applicationYear: "Application year",
      deadline: "Deadline",
      notes: "Notes",
      officialSource: "Official source",
      pdf: "Documents (PDF)",
      missing: "Missing fields",
      location: "Location (France)",
      specialties: "Specialties",
    },
    internal: "Internal selection by the French university",
    lsac: "LSAC platform",
    externalAccepted: "External applications accepted",
    externalRejected: "External applications not accepted",
    open: "Open",
  },
  es: {
    unknown: "No comunicado",
    unofficialBadge: "Por confirmar – fuente estudiantil no oficial",
    nanterreWarning:
      "La información sobre los convenios de Université Paris Nanterre procede de un documento estudiantil no oficial y puede variar según la promoción. Las universidades asociadas, plazas, becas y condiciones deben confirmarse con el máster o la universidad.",
    studentWarning: (university: string) =>
      `La información sobre ${university} procede de una fuente estudiantil no oficial y debe confirmarse con la universidad o el programa.`,
    labels: {
      faculty: "Facultad",
      programType: "Tipo de programa",
      programName: "Nombre del programa",
      partnershipType: "Tipo de convenio",
      application: "Candidatura",
      partnerRegion: "País/continente asociado",
      duration: "Duración",
      language: "Idioma",
      requiredLevel: "Nivel requerido",
      summary: "Resumen",
      sourceNote: "Nota de la fuente",
      seatPolicy: "Política de plazas",
      selection: "Selección",
      internalCandidates: "Candidatos internos",
      externalCandidates: "Candidatos externos",
      admission: "Requisitos de admisión",
      degrees: "Títulos otorgados",
      nyBar: "Opción New York Bar",
      conditions: "Requisitos",
      extraFees: "Costes adicionales",
      documents: "Documentos requeridos",
      languageTests: "Pruebas de idioma",
      seats: "Plazas",
      fees: "Costes",
      financialAid: "Ayudas económicas",
      applicationYear: "Año de candidatura",
      deadline: "Fecha límite",
      notes: "Notas",
      officialSource: "Fuente oficial",
      pdf: "Documentos (PDF)",
      missing: "Campos pendientes",
      location: "Ubicación (Francia)",
      specialties: "Especialidades",
    },
    internal: "Selección interna por la universidad francesa",
    lsac: "Plataforma LSAC",
    externalAccepted: "Candidaturas externas aceptadas",
    externalRejected: "Candidaturas externas no aceptadas",
    open: "Abrir",
  },
  de: {
    unknown: "Nicht bekannt gegeben",
    unofficialBadge: "Zur Bestätigung – inoffizielle Studentenquelle",
    nanterreWarning:
      "Informationen über Partnerschaften mit der Université Paris Nanterre stammen aus einem inoffiziellen Studentendokument und können je nach Kohorte variieren. Partneruniversitäten, Sitze, Stipendien und Verfahren müssen mit dem Programm oder der Universität bestätigt werden.",
    studentWarning: (university: string) =>
      `Information about ${university} comes from unofficial student feedback and must be confirmed with the university or program.`,
    labels: {
      faculty: "Fakultät",
      programType: "Programmtyp",
      programName: "Programmname",
      partnershipType: "Art der Partnerschaft",
      application: "Anwendung",
      partnerRegion: "Partnerland/Kontinent",
      duration: "Dauer",
      language: "Sprache",
      requiredLevel: "Erforderliches Niveau",
      summary: "Zusammenfassung",
      sourceNote: "Quellenanmerkung",
      seatPolicy: "Sitzplatzpolitik",
      selection: "Auswahl",
      internalCandidates: "Interne Bewerber",
      externalCandidates: "Externe Bewerber",
      admission: "Zulassungsvoraussetzungen",
      degrees: "Abschlüsse verliehen",
      nyBar: "New York Bar-Option",
      conditions: "Anforderungen",
      extraFees: "Zusätzliche Gebühren",
      documents: "Erforderliche Dokumente",
      languageTests: "Sprachtests",
      seats: "Sitze",
      fees: "Gebühren",
      financialAid: "Finanzielle Hilfe",
      applicationYear: "Bewerbungsjahr",
      deadline: "Frist",
      notes: "Notizen",
      officialSource: "Offizielle Quelle",
      pdf: "Dokumente (PDF)",
      missing: "Fehlende Felder",
      location: "Standort (Frankreich)",
      specialties: "Spezialitäten",
    },
    internal: "Interne Auswahl durch die französische Universität",
    lsac: "LSAC-Plattform",
    externalAccepted: "Externe Bewerbungen werden angenommen",
    externalRejected: "Externe Bewerbungen werden nicht angenommen",
    open: "Offen",
  },
  it: {
    unknown: "Non divulgato",
    unofficialBadge: "Da confermare – fonte studentesca non ufficiale",
    nanterreWarning:
      "Le informazioni sui partenariati dell'Université Paris Nanterre provengono da un documento studentesco non ufficiale e possono variare tra le coorti. Le università partner, le sedi, le borse di studio e le procedure devono essere confermate con il programma o l'università.",
    studentWarning: (university: string) =>
      `Information about ${university} comes from unofficial student feedback and must be confirmed with the university or program.`,
    labels: {
      faculty: "Facoltà",
      programType: "Tipo di programma",
      programName: "Nome del programma",
      partnershipType: "Tipo di partenariato",
      application: "Applicazione",
      partnerRegion: "Paese/continente partner",
      duration: "Durata",
      language: "Lingua",
      requiredLevel: "Livello richiesto",
      summary: "Riepilogo",
      sourceNote: "Nota sulla fonte",
      seatPolicy: "Politica dei posti",
      selection: "Selezione",
      internalCandidates: "Candidati interni",
      externalCandidates: "Candidati esterni",
      admission: "Requisiti di ammissione",
      degrees: "Titoli rilasciati",
      nyBar: "Opzione Bar di New York",
      conditions: "Requisiti",
      extraFees: "Costi aggiuntivi",
      documents: "Documenti richiesti",
      languageTests: "Test di lingua",
      seats: "Sedili",
      fees: "Commissioni",
      financialAid: "Aiuto finanziario",
      applicationYear: "Anno di applicazione",
      deadline: "Scadenza",
      notes: "Note",
      officialSource: "Fonte ufficiale",
      pdf: "Documenti (PDF)",
      missing: "Campi mancanti",
      location: "Località (Francia)",
      specialties: "Specialità",
    },
    internal: "Selezione interna da parte dell'università francese",
    lsac: "Piattaforma LSAC",
    externalAccepted: "Si accettano candidature esterne",
    externalRejected: "Candidature esterne non accettate",
    open: "Aprire",
  },
} as const
